trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- job: WhatsNewUpdate
  displayName: '1. What s New Update'
  pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm run whatsNew'
    displayName: 'Whats new'
    env:
      AZURE_PULLREQUESTID: $(System.PullRequest.PullRequestId)

- job: TscBuild
  displayName: '2. Tsc Build'
  pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm run build'
    displayName: 'Tsc Build'